Prototype/onlineShopping/config/routes.rb
Rails.application.routes.draw do
  resources :items
  devise_for :users

  root 'home#index'
  get 'show/:id' => 'home#show'
  get 'item_managements/item_query' => 'item_managements#item_query'
  get 'item_managements/item_destroy/:id' => 'item_managements#item_destroy'
  get 'item_managements/item_new' => 'item_managements#item_new'
  post 'item_managements/item_create' => 'item_managements#item_create'
  patch 'item_managements/item_edit' => 'item_managements#item_edit'
  get 'item_managements/item_read/:id' => 'item_managements#item_read'
  get 'item_managements/item_show/:id' => 'item_managements#item_show'
  get 'home' => 'home#index'
  get 'home/result' => 'home#result'
  post 'home/search'=> 'home#search'
  patch 'home/buy' => 'home#buy'
  get 'home/trolley' => 'home#trolley'
  get 'home/delete_item_in_trolley/:id' => "home#delete_item_in_trolley"
  get 'home/trolley_clear' => "home#trolley_clear"
  post 'home/trolley_purchase' => "home#trolley_purchase"
  get 'order/my_orders' => 'orders#my_orders'
  get 'order/ask_cancel' => 'orders#ask_cancel'
  get 'order/pending_orders' => 'orders#pending_orders'
  get 'order/order_management' => 'orders#order_management'
  get 'order/approve_cancel' => 'orders#approve_cancel'

end

Prototype/onlineShopping/app/controllers/item_managements_controller.rb
class ItemManagementsController < ApplicationController
  #find items belong to current user
  def item_query
    @items_list = Item.query_with_owner_id current_user.id
  end

  #delete one of the item
  def item_destroy
    Item.delete_with_id params[:id]
    redirect_to item_managements_item_query_path
  end

  #show detail info of a selected item (editable)
  def item_show
    @record = Item.query_with_item_id params[:id]
    if @record[:owner_id].eql?(current_user.id)
    else
      flash[:error] = "This item doesn't belong to you!"
      redirect_to root_path
    end
  end

  #create a new item
  def item_new
    @new_item = Item.new
  end

  #save the params in the new created item
  def item_create
    Item.create_an_item params
    redirect_to item_managements_item_query_path
  end

  #show detail info of a selected item (can't edit)
  def item_read
    @record = Item.query_with_item_id params[:id]
    if @record[:owner_id].eql?(current_user.id)
    else
      flash[:error] = "This item doesn't belong to you!"
      redirect_to root_path
    end
  end

  #udpate the info of an item
  def item_edit
    Item.edit_an_item params
    redirect_to item_managements_item_query_path
  end
end

Prototype/onlineShopping/app/helpers/item_managements_helper.rb
module ItemManagementsHelper
end

Prototype/onlineShopping/app/views/item_managements/item_new.html.erb
<h1>Item Create</h1>
<%= form_for(@new_item, :url => {:action => "item_create"}) do |f| %>
  <%= f.hidden_field :owner_id, :value => current_user.id %>
  <div class="field">
    <%= f.label 'Item name' %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label 'Item quantity' %><br>
    <%= f.text_field :quantity %>
  </div>
  <div class="field">
    <%= f.label 'Item price' %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label 'Item description' %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  </br>
  <%= link_to "Back", item_managements_item_query_path%>
<%end%>

Prototype/onlineShopping/app/views/item_managements/item_query.html.erb
<h1>Item Management</h1>
<div>
  <div name = "list_head">
  <%= link_to 'Create', item_managements_item_new_path%>
  </br>
  <%= link_to "Back", root_path%>
  <h4>My items</h4>
  </div>
  <div name = "list_doby">
    <table name = "my_item_list">
      <thead>
        <tr>
          <th>Item Number</th>
          <th>Name</th>
          <th>Price</th>
          <th>Quantity</th>
          <th>Action</th>
        </tr>
      </thead>
      <% count =0 %>
      <tbody>
      <% @items_list.each do |item| %>
          <tr>
              <td><%= count+=1 %></td>         
              <td><%= link_to item.name, "item_show/#{item.id}"%></td>
              <td><%= item.price %></td>
              <td><%= item.quantity %></td>  
              <td><%= link_to "edit", "item_read/#{item.id}"%>
              <%= link_to "destroy", "item_destroy/#{item.id}", data: { confirm: 'Are you sure?' } %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

Prototype/onlineShopping/app/views/item_managements/item_read.html.erb
<h1>Item Edit</h1>
<%= form_for(@record, :url => {:action => "item_edit"}) do |f| %>
  <%= f.hidden_field :owner_id, :value => current_user.id %>
  <%= f.hidden_field :id, :value => @record[:id] %>
  <div class="field">
    <%= f.label 'Item name' %><br>
    <%= f.text_field :name, :value => @record[:name] %>
  </div>
  <div class="field">
    <%= f.label 'Item quantity' %><br>
    <%= f.text_field :quantity, :value => @record[:quantity] %>
  </div>
  <div class="field">
    <%= f.label 'Item price' %><br>
    <%= f.text_field :price, :value => @record[:price] %>
  </div>
  <div class="field">
    <%= f.label 'Item description' %><br>
    <%= f.text_area :description, :value => @record[:description] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  </br>
  <%= link_to "Back", item_managements_item_query_path%>
<%end%>

Prototype/onlineShopping/app/views/item_managements/item_show.html.erb
<h1>Item Info</h1>
<%= form_for(@record) do |f| %>
  <%= f.hidden_field :owner_id, :value => current_user.id %>
  <div class="field">
    <%= f.label 'Item name' %><br>
    <%= @record[:name] %>
  </div>
  <div class="field">
    <%= f.label 'Item quantity' %><br>
    <%= @record[:quantity]%>
  </div>
  <div class="field">
    <%= f.label 'Item price' %><br>
    <%= @record[:price]%>
  </div>
  <div class="field">
    <%= f.label 'Item description' %><br>
    <%= @record[:description] %>
  </div>
  <div class="actions">
    <%= link_to "edit", "/item_managements/item_read/#{@record.id}" %>
  </div>
  </br>
  <%= link_to "Back", item_managements_item_query_path%>
<%end%>