Prototype/onlineShopping/config/routes.rb
Rails.application.routes.draw do
  resources :items
  devise_for :users

  root 'home#index'
  get 'show/:id' => 'home#show'
  get 'item_managements/item_query' => 'item_managements#item_query'
  get 'item_managements/item_destroy/:id' => 'item_managements#item_destroy'
  get 'item_managements/item_new' => 'item_managements#item_new'
  post 'item_managements/item_create' => 'item_managements#item_create'
  patch 'item_managements/item_edit' => 'item_managements#item_edit'
  get 'item_managements/item_read/:id' => 'item_managements#item_read'
  get 'item_managements/item_show/:id' => 'item_managements#item_show'
  get 'home' => 'home#index'
  get 'home/result' => 'home#result'
  post 'home/search'=> 'home#search'
  patch 'home/buy' => 'home#buy'
  get 'home/trolley' => 'home#trolley'
  get 'home/delete_item_in_trolley/:id' => "home#delete_item_in_trolley"
  get 'home/trolley_clear' => "home#trolley_clear"
  post 'home/trolley_purchase' => "home#trolley_purchase"
  get 'order/my_orders' => 'orders#my_orders'
  get 'order/ask_cancel' => 'orders#ask_cancel'
  get 'order/pending_orders' => 'orders#pending_orders'
  get 'order/order_management' => 'orders#order_management'
  get 'order/approve_cancel' => 'orders#approve_cancel'

end

Prototype/onlineShopping/app/models/order.rb
class Order < ActiveRecord::Base
  #update the info of purchased items
  def self.purchase(list, quantity)
    result = []
    list.each do |item_id|
      aim_item = Item.find(item_id.to_i)
      session_temp = nil
      quantity.each do |item_quantity|
        if item_id.to_i.eql?(item_quantity["item_buy"].to_i)
          session_temp = item_quantity
          session_temp["name"] = aim_item[:name]
          session_temp["price"] = aim_item[:price]
        end
      end
      quantity_temp = session_temp["quantity_buy"].to_i
      aim_item[:quantity] = aim_item[:quantity] - quantity_temp
      aim_item.save
      result << session_temp
    end
    return result
  end

  #create an order in the database
  def self.create_order params 
    @order = Order.new
    @order[:buyer] = params["buyer"]
    @order[:items] = params["items"]
    @order[:totalprice] = params["totalprice"]
    @order.save
  end

  #find the order with its id
  def self.list_order id
    @orders = Order.where(:buyer => id)
    return @orders     
  end
end

Prototype/onlineShopping/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  #list orders belong to current user
  def my_orders
    @my_orders = Order.list_order current_user[:id]
  end

  #quest for cancel an order
  def ask_cancel
    @pending_order = Order.find(params[:format].to_i)
    PendingOrder.createPendingOrder @pending_order
    Order.delete(@pending_order)
    redirect_to order_my_orders_path
  end

  #list pending orders belong to current user
  def pending_orders
    @pending_orders = PendingOrder.pendingOrder current_user[:id].to_i
  end

  #list all pending orders
  def order_management
    @pending_orders = PendingOrder.all_orders
  end

  #approve cancel of selected item
  def approve_cancel
    @aim_order = PendingOrder.approve params[:format]
    redirect_to order_order_management_path
  end
end

Prototype/onlineShopping/app/helpers/orders_helper.rb
module OrdersHelper
end

Prototype/onlineShopping/app/views/orders/my_orders.html.erb
<h1>Orders</h1>
<div>
  <div name = "order_list_head">
  <%= link_to "Back", root_path%>
  <h4>My orders</h4>
  </div>
  <div name = "list_doby">
  <% if !@my_orders.empty?%>
    <table name = "my_orders_list">
      <thead>
        <tr>
          <th>OrderID</th>
          <th>Items</th>
          <th>CreatedTime</th>
          <th>Total</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
      <% @my_orders.each do |order| %>
        <% temp_list = eval order[:items]%>
        <% content = ""%>
        <% temp_list.each do |item|%>
          <% aim_item = Item.find(item["item_buy"])%>
          <% content = content + aim_item[:name] + "*" +item["quantity_buy"].to_s + " "%>
        <% end%>
          <tr>
              <td><%= order[:id] %></td>   
              <td><%= content%></td>      
              <td><%= order[:created_at]%></td>
              <td><%= order[:totalprice] %></td> 
              <td><%= link_to "Cancel", order_ask_cancel_path(order[:id]), data: { confirm: 'The order will be moved to pending order list, continue?' }%></td>
          </tr>
      <% end %>
      </tbody>
    </table>
    <%else%>
    <h3>You don't have any orders now</h3>
    <%end%>
  </div>
</div>

Prototype/onlineShopping/app/views/orders/order_management.html.erb
<h1>Orders</h1>
<div>
  <div name = "order_list_head">
  <%= link_to "Back", root_path%>
  <h4>Pengding orders</h4>
  </div>
  <div name = "list_doby">
  <% if !@pending_orders.empty?%>
    <table name = "my_orders_list">
      <thead>
        <tr>
          <th>Client</th>
          <th>Items</th>
          <th>CreatedTime</th>
          <th>CancelTime</th>
          <th>Total</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
      <% @pending_orders.each do |order| %>
        <% temp_list = eval order[:items]%>
        <% content = ""%>
        <% temp_list.each do |item|%>
          <% aim_item = Item.find(item["item_buy"])%>
          <% content = content + aim_item[:name] + "*" +item["quantity_buy"].to_s + " "%>
        <% end%>
          <tr>
              <td><%= User.find(order[:buyer])[:email] %></td>   
              <td><%= content%></td>      
              <td><%= order[:purchasetime]%></td>
              <td><%= order[:created_at]%></td>
              <td><%= order[:totalprice] %></td> 
              <td><%= link_to "Approve", order_approve_cancel_path(order[:id])%></td>
          </tr>
      <% end %>
      </tbody>
    </table>
    <%else%>
    <h3>No pending orders now</h3>
    <%end%>
  </div>
</div>

Prototype/onlineShopping/app/views/orders/pending_orders.html.erb
<h1>Orders</h1>
<div>
  <div name = "order_list_head">
  <%= link_to "Back", root_path%>
  <h4>Pengding orders</h4>
  </div>
  <div name = "list_doby">
  <% if !@pending_orders.empty?%>
    <table name = "my_orders_list">
      <thead>
        <tr>
          <th>OrderID</th>
          <th>Items</th>
          <th>CreatedTime</th>
          <th>CancelTime</th>
          <th>Total</th>
        </tr>
      </thead>
      <tbody>
      <% @pending_orders.each do |order| %>
        <% temp_list = eval order[:items]%>
        <% content = ""%>
        <% temp_list.each do |item|%>
          <% aim_item = Item.find(item["item_buy"])%>
          <% content = content + aim_item[:name] + "*" +item["quantity_buy"].to_s + " "%>
        <% end%>
          <tr>
              <td><%= order[:id] %></td>   
              <td><%= content%></td>      
              <td><%= order[:purchasetime]%></td>
              <td><%= order[:created_at]%></td>
              <td><%= order[:totalprice] %></td> 
          </tr>
      <% end %>
      </tbody>
    </table>
    <%else%>
    <h3>You don't have any pending orders now</h3>
    <%end%>
  </div>
</div>