Prototype/onlineShopping/config/routes.rb
Rails.application.routes.draw do
  resources :items
  devise_for :users

  root 'home#index'
  get 'show/:id' => 'home#show'
  get 'item_managements/item_query' => 'item_managements#item_query'
  get 'item_managements/item_destroy/:id' => 'item_managements#item_destroy'
  get 'item_managements/item_new' => 'item_managements#item_new'
  post 'item_managements/item_create' => 'item_managements#item_create'
  patch 'item_managements/item_edit' => 'item_managements#item_edit'
  get 'item_managements/item_read/:id' => 'item_managements#item_read'
  get 'item_managements/item_show/:id' => 'item_managements#item_show'
  get 'home' => 'home#index'
  get 'home/result' => 'home#result'
  post 'home/search'=> 'home#search'
  patch 'home/buy' => 'home#buy'
  get 'home/trolley' => 'home#trolley'
  get 'home/delete_item_in_trolley/:id' => "home#delete_item_in_trolley"
  get 'home/trolley_clear' => "home#trolley_clear"
  post 'home/trolley_purchase' => "home#trolley_purchase"
  get 'order/my_orders' => 'orders#my_orders'
  get 'order/ask_cancel' => 'orders#ask_cancel'
  get 'order/pending_orders' => 'orders#pending_orders'
  get 'order/order_management' => 'orders#order_management'
  get 'order/approve_cancel' => 'orders#approve_cancel'

end

Prototype/onlineShopping/app/controllers/home_controller.rb
class HomeController < ApplicationController
  $item_list = []

  #show all the item in the database
  def index
    $item_list = Item.all
  end

  #show detail info about the selected item
  def show
    @item = Item.query_with_item_id params[:id]
    @seller = User.find(@item[:owner_id])[:email]
    @buyer = current_user
  end

  #find the items with the key word
  def search
    $item_list = Item.search params[:search]
    redirect_to home_result_path
  end

  #just list the result, no domain logic here
  def result
  end

  #put the selected item into shopping trolley
  def buy
    @flag = false
    session[:item].each do |itemp|
    # if the item exists in the session, just add the quantity
      if itemp["item_buy"].eql?(params[:item][:item_id])
        itemp["quantity_buy"] = itemp["quantity_buy"].to_i + params[:item][:quantity].to_i
        @flag = true
      end
    end
    # if the item doesn't exist, push the item in the session
    if @flag == false
      @item_hash = {"item_buy" => params[:item][:item_id], "quantity_buy" => params[:item][:quantity]}
      session[:item].push @item_hash
      puts session[:item]
    end
    redirect_to root_path
  end

  #list all the items in the shopping trolley
  def trolley
    #the list of items in the trolley to store returned items
    $item_in_trolley = []
    if !session[:item].blank?
      #get all items in the trolley from database with info in session
      session[:item].each do |item_temp|
        @item_temp = item_temp
        @item = Item.query_with_item_id item_temp["item_buy"].to_i
        $item_in_trolley<<@item
      end
    else
      #no domain logic need here
    end
  end

  #delete all the items in the shopping trolley
  def trolley_clear
    session[:item] = []
    redirect_to home_trolley_path
  end

  #delete selected item in the shopping trolley
  def delete_item_in_trolley
    session[:item].each do |item|
      if item["item_buy"].to_s.eql?(params[:id])
        session[:item].delete(item)
      end
    end
    redirect_to home_trolley_path
  end

  #purchase selected items in the shopping trolley
  def trolley_purchase
    @order_info = {}
    @totalprice = 0
    @flag = true
    params["item_id"].each do |aim_item_info|  
      aim_item = Item.find(aim_item_info.to_i)
      if aim_item[:owner_id].eql?current_user[:id]
        @flag = false
        flash[:error] = "You can't buy your own item #{aim_item[:name]}, please modify your order."
      end
      aim_item_session = nil
      session[:item].each do |temp|
        if aim_item[:id].eql?(temp["item_buy"].to_i)
          aim_item_session = temp
        end
      end
      aim_item_quantity = aim_item_session["quantity_buy"].to_i
      # if a buyer wants to get more than the seller has, the system throws an error
      if aim_item[:quantity] < aim_item_quantity
        flash[:error] = "Only #{aim_item[:quantity]} #{aim_item[:name]} left, please modify your order."
        @flag = false
      else
        @totalprice = @totalprice + aim_item[:price] * aim_item_quantity
      end
    end

    if @flag
    ##########################################################
      @items = Order.purchase(params["item_id"], session[:item])
      @order_info["buyer"] = current_user[:id]
      @order_info["items"] = @items
      @order_info["totalprice"] = @totalprice
      Order.create_order @order_info
      flash[:success] = "A new order has been created!"
      #delete purchased items in the session#################
      params["item_id"].each do |delete_aim|
        session[:item].each do |delete_session|
          if delete_session["item_buy"].to_i.eql?(delete_aim.to_i)
            session[:item].delete(delete_session)
          end
        end
      end
    #######################################################
    end
    redirect_to home_trolley_path
  end
end

Prototype/onlineShopping/app/views/home/_search.html.erb
<%= form_tag :controller => 'home', :action => 'search', :method => 'get' do %>
  <%= text_field_tag :search, params[:search], :id => 'search_field' %>
  <%= submit_tag "Search", :name => nil %> 
<% end %>

Prototype/onlineShopping/app/views/home/index.html.erb
<h1>Online shopping system prototype</h1>
<% if user_signed_in?%>
  <% @user = User.find(current_user[:id])  %>
  <% if @user[:admin] == false%>
    Hello, <%= current_user.email %><br />
    <%= link_to('Trolley', home_trolley_path, data: { no_turbolink: true }) %><br />
    <%= link_to('Item Manage', item_managements_item_query_path) %><br />
    <%= link_to('My Orders', order_my_orders_path) %><br />
    <%= link_to('Pending Orders', order_pending_orders_path) %><br />
    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
  <%else%>
    <%= link_to('Order Management', order_order_management_path)%><br/>
    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
  <%end%>
<% else %>
  <%session[:item] = []%>
  <%= link_to('Register', new_registration_path(:user)) %><br />
  <%= link_to('Login', new_session_path(:user)) %>
<%end%>
<div id="search">
  <%= render :partial => 'home/search' %>
</div>

<h2>Item list</h2>
<div name = "list_doby">
  <table name = "my_item_list">
    <thead>
      <tr>
        <th>Name</th>
        <th>Price</th>
      </tr>
    </thead>

    <tbody>
    <% $item_list.each do |item| %>
        <tr>       
            <td><%= link_to item.name, "show/#{item.id}"%></td>
            <td><%= item.price %></td> 
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

Prototype/onlineShopping/app/views/home/result.html.erb
<h1>Online shopping system prototype</h1>
<% if user_signed_in?%>
  <% @user = User.find(current_user[:id])  %>
  <% if @user[:admin] == false%>
    Hello, <%= current_user.email %><br />
    <%= link_to('Trolley', home_trolley_path, data: { no_turbolink: true }) %><br />
    <%= link_to('Item Manage', item_managements_item_query_path) %><br />
    <%= link_to('My Orders', order_my_orders_path) %><br />
    <%= link_to('Pending Orders', order_pending_orders_path) %><br />
    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
  <%else%>
    <%= link_to('Order Management', order_order_management_path)%><br/>
    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
  <%end%>
<% else %>
  <%session[:item] = []%>
  <%= link_to('Register', new_registration_path(:user)) %><br />
  <%= link_to('Login', new_session_path(:user)) %>
<%end%>
<div id="search">
  <%= render :partial => 'home/search' %>
</div>

<h2>Item list</h2>
<div name = "list_doby">
  <table name = "my_item_list">
    <thead>
      <tr>
        <th>Name</th>
        <th>Price</th>
      </tr>
    </thead>

    <tbody>
    <% $item_list.each do |item| %>
        <tr>       
            <td><%= link_to item.name, "/show/#{item.id}"%></td>
            <td><%= item.price %></td> 
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

Prototype/onlineShopping/app/views/home/show.html.erb
<h1>Item Info</h1>
<%= form_for(@item, :url => {:action => "buy"}) do |f| %>
<%= f.hidden_field :item_id, :value => @item[:id] %>
  <div class="field">
    <%= f.label 'Item name' %><br>
    <%= @item[:name] %>
  </div>
  <br>
  <div class="field">
    <%= f.label 'Item quantity' %><br>
    <%= @item[:quantity]%>
  </div>
  <br>
  <div class="field">
    <%= f.label 'Item price' %><br>
    <%= @item[:price] %>
  </div>
  <br>
  <div class="field">
    <%= f.label 'Item description' %><br>
    <%= @item[:description] %>
  </div>
  <br>
    <div class="field">
    <%= f.label 'Seller email' %><br>
    <%= link_to @seller%>
  </div>
  <% if !user_signed_in? %>
  <% elsif @buyer[:admin] == true%>
  <% else %>  
    <br>
    <%= f.label 'Quantity to buy:' %><br>
    <% if @item[:quantity]>0%>
    <%= f.number_field :quantity, value:1, min: 1, max: @item[:quantity]%>
    <%= submit_tag "Buy" %>
    <% else %>
    Sorry, Out of stock now.
    <% end %>
  <% end %>
  <br>
  <%= link_to "Back", home_path%>
<% end %>

Prototype/onlineShopping/app/views/home/trolley.html.erb
<h2>My trolley</h2>
<div name = "list_doby">
    <%= link_to "Back", root_path%>

    <% if !$item_in_trolley.empty?%>
        <%= link_to "Clear", home_trolley_clear_path%>
    <table name = "my_item_list">
        <thead>
            <tr>
              <th>Purchase</th>
              <th>Name</th>
              <th>Price</th>
              <th>Quantity</th>
              <th>Total</th>
              <th>Action</th>
            </tr>
        </thead>

        <tbody>
            <%= form_tag(home_trolley_purchase_path) do %>
                <% for item in $item_in_trolley%>
                  <% aim = 0%>
                  <% for iqi in session[:item] %>
                    <% aim = iqi.values[1] if iqi.values[0].to_i.eql?(item[:id])%>
                  <% end %>
                  <tr>
                    <td><%= check_box_tag "item_id[]", item[:id] %></td>
                    <td><%= link_to item.name, "/show/#{item.id}" %></td>
                    <td><%= item[:price]%></td>
                    <td><%= aim%></td>
                    <td><%= item[:price]*aim.to_f%></td>
                    <td><%= link_to "Delete", "/home/delete_item_in_trolley/#{item[:id]}"%></td>
                  </tr>
                <% end %>
               <%= submit_tag "Purchase checked items"%> 
            <% end %>
        </tbody>
    </table>
    <% else%>
        <h3>No item in trolley</h3>
    <% end%>
</div>